### PR TITLE
Test/update docs

### PR DESCRIPTION
**Pull request by stevemom-repay**

### CODE REVIEW

**Comment by wilysword** [comment]
@mikesoltow Should we be reviewing this PR, or close it?

**Comment by mikesoltow** [comment]
@wilysword Yeah, I'd like to review it.  I've just been putting it off.  But I'll try to get to it by next week.  Feel free to take a look and review with your thoughts if you'd like.

**Review by wilysword — COMMENTED** [review]
The information in these docs seems generally useful; there are missing examples, of course, and it's rather incongruous that the examples are all in Python considering this is a JavaScript repo. Before merging, someone would likely need to go through and fix the existing examples, and add missing ones.

I'm also not clear on why he removed the how-to on End-to-End Testing, since that seems to cover significantly different information.

**Review by luisniebla — APPROVED** [review]
LGTM

**Pull request closed without merging**
