### PR TITLE
Cactus 510 modals issue

### PR DESCRIPTION
**Pull request by daniloPenaR**
[Cactus-510](https://repayonline.atlassian.net/browse/CACTUS-510)

### CODE REVIEW

**Review by Dhalton — COMMENTED** [review]
LGTM but I think you need to delete the storyshots that were added -- it doesn't look like they're associated with a story that we can test against.

**Review by mikesoltow — COMMENTED** [review]
Yeah, I'm a bit confused about the storyshots myself.  How did you generate them without having an associated story?  If you deleted the associated story, I'd recommend bringing it back before we merge.  That will allow the automated tests to run against your screenshots and allow Emily to properly UAT.

**Comment by daniloPenaR** [comment]
> Yeah, I'm a bit confused about the storyshots myself. How did you generate them without having an associated story? If you deleted the associated story, I'd recommend bringing it back before we merge. That will allow the automated tests to run against your screenshots and allow Emily to properly UAT.

I know what happened, I created a new story to reproduce the steps and see the error. I guess that I ran the `test:build` and `test:docker-update` before deleting that story. Shame on me.

**Comment by mikesoltow** [comment]
> > Yeah, I'm a bit confused about the storyshots myself. How did you generate them without having an associated story? If you deleted the associated story, I'd recommend bringing it back before we merge. That will allow the automated tests to run against your screenshots and allow Emily to properly UAT.
> 
> I know what happened, I created a new story to reproduce the steps and see the error. I guess that I ran the `test:build` and `test:docker-update` before deleting that story. Shame on me.

No big deal!  My recommendation would be to keep the images and add the story back in...as I think it's a useful test case.

**Comment by daniloPenaR** [comment]
> > > Yeah, I'm a bit confused about the storyshots myself. How did you generate them without having an associated story? If you deleted the associated story, I'd recommend bringing it back before we merge. That will allow the automated tests to run against your screenshots and allow Emily to properly UAT.
> > 
> > 
> > I know what happened, I created a new story to reproduce the steps and see the error. I guess that I ran the `test:build` and `test:docker-update` before deleting that story. Shame on me.
> 
> No big deal! My recommendation would be to keep the images and add the story back in...as I think it's a useful test case.

I already added the story and updated their storyshots.

**Review by mikesoltow — APPROVED** [review]
Thanks, Danilo!

**Review by Dhalton — APPROVED** [review]
LGTM nice work!

**Pull request merged**
