### PR TITLE
CACTUS-405 :: IE relatedTarget Support

### PR DESCRIPTION
**Pull request by Dhalton**
https://repayonline.atlassian.net/browse/CACTUS-405

Should be a quick & easy one. I tested other usages of `relatedTarget` that I found, but I didn't notice any problems. If you happen to notice anything I missed, let me know!

### Testing
Test the following in both IE and your preferred browser
1. Open the Select "with comboBox" story and focus the combobox input. Click outside the select and make sure the list closes.
2. Open the Layout story and click the gear icon in the action bar. Click outside the panel to make sure it closes when focus leaves the panel.

### CODE REVIEW

**Review by mikesoltow — APPROVED** [review]
LGTM

**Review by wilysword — APPROVED** [review]

**Comment by Dhalton** [comment]
@wilysword @mikesoltow You guys may want to re-review this before it gets merged; because the logic in `usePopup` changed a bit, I don't think there's a need to explicitly check the React version anymore. `focused` defaults to `event.relatedTarget` anyway. I did keep the change to the wording of the comment, though.

**Comment by wilysword** [comment]
I'm fine with it, given that I'm the one who wrote it that way to begin with. (And in the feature branch that bit of code was moved to a different file anyway...yay merge conflict waiting to happen!)

**Comment by mikesoltow** [comment]
I'm fine with this too!

**Pull request merged**
