### PR TITLE
CACTUS-661 :: Flatten Action Colors

### PR DESCRIPTION
**Pull request by mikesoltow**
Ticket and UAT: https://repayonline.atlassian.net/browse/CACTUS-661

Note that, with Hector's approval, I ditched the box shadow on the Modal.  You couldn't really see it anyway in the old version, since it was a transparent color over a very dark background.  The new shadow, because it's no longer transparent, just looked weird and bright against the dark background (see attached screenshot).  So we just got rid of it.
Screen Shot 2021-07-14 at 3 05 57 PM

Otherwise, there should be no visible changes to any components.

### CODE REVIEW

**Comment by daniloPenaR** [comment]
Screen Shot 2021-07-15 at 11 35 54 AM
Screen Shot 2021-07-15 at 11 36 09 AM

The box-shadow in cards is no longer visible, is that part of the Modal's box-shadow change you made?

**Comment by mikesoltow** [comment]
@daniloPenaR I'm double-checking now, but did you rebuild the theme before starting storybook?  It's possible the new theme colors just aren't being pulled in.

**Comment by daniloPenaR** [comment]
Nevermind, I built again the project and that was the problem.

**Review by daniloPenaR — APPROVED** [review]
I tested it, seems to be good.

**Review by Dhalton — APPROVED** [review]
LGTM

**Pull request merged**
