### PR TITLE
CACTUS-656 :: UserMenu Z-Index

### PR DESCRIPTION
**Pull request by Dhalton**
Ticket: https://repayonline.atlassian.net/browse/CACTUS-656

### Testing
1. Pull down this branch and start storybook.
2. Bring up the Layout > Short Content story.
3. Open the user menu and make sure the dropdown is rendered above the items in the menu bar

### CODE REVIEW

**Review by wilysword — APPROVED** [review]

**Comment by wilysword** [comment]
I'm fine with this, just pointing out this is going to be made obsolete and/or require a different fix in https://github.com/repaygithub/cactus/pull/597.

**Review by daniloPenaR — APPROVED** [review]
LGTM.

**Comment by Dhalton** [comment]
We should hold off on merging this since, as Glen mentioned, there will likely need to be some updates because of the changes to UserMenuItem.

**Comment by mikesoltow** [comment]
I think this PR is now completely obsolete after Danilo's.  I used `yalc` to test the `cactus-web-v7` branch in Channels and compared it to UAT, with the following results.  If someone wants to check my work, I'd appreciate it.  But from what I can tell, this can be closed (sorry Dhalton!).

cactus-web-v7:
Screen Shot 2021-07-01 at 5 16 45 PM

UAT:
Screen Shot 2021-07-01 at 5 16 57 PM

**Comment by Dhalton** [comment]
> I think this PR is now completely obsolete after Danilo's.

I tested in storybook and you're right! 🎉  So I'll just close this then.

**Pull request closed without merging**
