### PR TITLE
Revert "Go back to running BrowserStack tests in parallel"

### PR DESCRIPTION
**Pull request by mikesoltow**
😢

### CODE REVIEW

**Review by NicolasSimmonds — APPROVED** [review]
😢

**Comment by Dhalton** [comment]
Did this fail because Glen's PR is trying to run integration tests maybe?

**Comment by mikesoltow** [comment]
That would be my guess.  It's still not foolproof, but it cuts in half the resources our integration tests will take up.

**Comment by Dhalton** [comment]
Yeah. Glen's has been stuck on integration tests for almost 2 hours so maybe we should cancel that run...

**Comment by mikesoltow** [comment]
> Yeah. Glen's has been stuck on integration tests for almost 2 hours so maybe we should cancel that run...

Done

**Review by Dhalton — APPROVED** [review]

**Pull request merged**
