### PR TITLE
CACTUS-412 MenuBar scroll buttons are both visible or both hidden

### PR DESCRIPTION
**Pull request by wilysword**
https://repayonline.atlassian.net/browse/CACTUS-412

I looked into using IconButton like the ticket said, but it didn't work out:
- The icons are 18px, which is not an available `IconSize`. Looking at the code I think you could actually pass `iconSize="18px"` and it would work, but you'd have to do `@ts-ignore` _and_ you'd still get a PropTypes warning.
- (I had more reasons, but when I considered them more deeply while writing them out here, I realized they weren't as good as I thought they were.)

### CODE REVIEW

**Review by Dhalton — APPROVED** [review]
LGTM!

**Review by mikesoltow — APPROVED** [review]
LGTM

Completely unrelatedly, I can't remember if I asked you about the fact that, if you click on a menu item that has a dropdown, there's a quick flash of an outline before the dropdown appears.  I wonder if we need a ticket to look at that?

**Comment by wilysword** [comment]
Are you talking about the outline on the button that you clicked on? That's because when you click the button it gets focus, and then focus shifts to the submenu so that you can use the arrow keys to navigate.

**Comment by mikesoltow** [comment]
> Are you talking about the outline on the button that you clicked on? That's because when you click the button it gets focus, and then focus shifts to the submenu so that you can use the arrow keys to navigate.

Yeah.  Makes sense...it just looks a bit weird, so it might be worth looking into.

**Pull request merged**
