### PR TITLE
CACTUS-408 :: stop passing custom prop to DOM element in Accordion

### PR DESCRIPTION
**Pull request by mikesoltow**
Ticket and testing: https://repayonline.atlassian.net/browse/CACTUS-408

### CODE REVIEW

**Review by wilysword — APPROVED** [review]
I realize this would technically be scope creep, but since it's a small change would you be up for fixing the other warning we get during unit tests? I think it's on Breadcrumb, if I recall correctly...

**Comment by mikesoltow** [comment]
> I realize this would technically be scope creep, but since it's a small change would you be up for fixing the other warning we get during unit tests? I think it's on Breadcrumb, if I recall correctly...

Sure thing...I'll take a look.

**Comment by mikesoltow** [comment]
@wilysword I'm not seeing a log message for another component, either on my computer or by scrolling the GitHub action logs.  Are you able to see an additional log with the latest changes?  If so let me know, and I'll take another look.

**Comment by mikesoltow** [comment]
> @wilysword I'm not seeing a log message for another component, either on my computer or by scrolling the GitHub action logs. Are you able to see an additional log with the latest changes? If so let me know, and I'll take another look.

Never mind, I found it.  It's only on the `cactus-web-v4` branch

**Comment by mikesoltow** [comment]
@wilysword I just updated this.  Because the error you mentioned was only on `cactus-web-v4`, I rebase/force pushed/re-targeted the PR.

**Review by wilysword — APPROVED** [review]

**Review by Dhalton — APPROVED** [review]
LGTM

**Pull request merged**
